### ISSUE TITLE
SAC端创建主机失败

### ISSUE THREAD

**Issue by kvnzhang** [SequoiaDB/SequoiaDB_OLD#73]
我部署的是独立模式，SAC创建主机时提示如下信息，检查错误码是超时，但是按照官方提示用setSessionAttr()延长超时时间，还是没有解决问题，请问怎么检查和排除这个问题？

”获取数据失败
执行命令: scan host, 错误码: -13, send message to agent failed:rc=-13。需要重试吗?”

**Comment by x56080** [comment]
出现该错误是om连不上本身的cm（即 om agent）节点，存在以下的可能原因：
1、本地 cm 没有启动； 
      诊断：可以通过 bin/sdblist -t cm 查看 cm 是否启动；
      解决方法：如果 cm 没有启动，可以通过 bin/sdbcmart 启动 cm 即可。

**Comment by kvnzhang** [comment]
> 出现该错误是om连不上本身的cm（即 om agent）节点，存在以下的可能原因：
> 1、本地 cm 没有启动；
> 诊断：可以通过 bin/sdblist -t cm 查看 cm 是否启动；
> 解决方法：如果 cm 没有启动，可以通过 bin/sdbcmart 启动 cm 即可。
CM已经启动了，如下。
[root@dbserver1 tst]# /opt/sequoiadb/bin/sdblist -t cm
sdbcm(11790) (1588) 
sdbcmd (929)
Total: 2

**Comment by x56080** [comment]
可以看一下 om 节点的诊断日志( diaglog 日志 )，会有详细的错误信息；
diaglog 路径为 om的 数据目录/diaglog；
通过 bin/sdblist -l -t om 可以查看 om 的 数据目录。

**Comment by kvnzhang** [comment]
多谢指点，通过查看log（如下）发现独立模式尽然本地直接用域名localhost连接（不知道是否是一个Bug，因为根据你们的安装配置文档，我把localhost替换成了dbserver1），然后在/etc/hosts里面添加localhost映射，问题解决！

2019-12-18-05.58.07.266982               Level:ERROR
PID:1631                                 TID:1868
Function:syncConnect                     Line:363
File:SequoiaDB/engine/net/netEventHandler.cpp
Message:
Connection[Handle:11] connect to localhost:11790(11790) failed, rc: -13
